services:

  web:
    build: .
    command: ["./wait-for-it.sh","db:5432","--","gunicorn","myshop.wsgi:application","--bind","0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB=myshop
      - POSTGRES_USER=myshop
      - POSTGRES_PASSWORD=myshop
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
      - rabbitmq
  
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myshop
      POSTGRES_USER: myshop
      POSTGRES_PASSWORD: myshop
  
  redis:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "15672:15672"  # ui
      - "5672:5672"   # amqp
  
  celery:
    build: .
    command: celery -A myshop worker --loglevel=info
    depends_on:
      - web
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
  
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes: 
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web