services:
  - type: web
    name: myshop-web
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker-compose build web

  - type: worker
    name: myshop-celery
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker-compose build celery
    
