[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=10
autostart=true
autorestart=true

[program:gunicorn]
directory=/code
command=gunicorn myshop.wsgi:application --bind 127.0.0.1:8000
priority=20
autostart=true
autorestart=true
