# Generated by Django 5.0.14 on 2025-06-23 14:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
